// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sema/raft/pkg/actor (interfaces: ServerGateway)

// Package mock_actor is a generated GoMock package.
package mock_actor

import (
	gomock "github.com/golang/mock/gomock"
	actor "github.com/sema/raft/pkg/actor"
	reflect "reflect"
)

// MockServerGateway is a mock of ServerGateway interface
type MockServerGateway struct {
	ctrl     *gomock.Controller
	recorder *MockServerGatewayMockRecorder
}

// MockServerGatewayMockRecorder is the mock recorder for MockServerGateway
type MockServerGatewayMockRecorder struct {
	mock *MockServerGateway
}

// NewMockServerGateway creates a new mock instance
func NewMockServerGateway(ctrl *gomock.Controller) *MockServerGateway {
	mock := &MockServerGateway{ctrl: ctrl}
	mock.recorder = &MockServerGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockServerGateway) EXPECT() *MockServerGatewayMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockServerGateway) Send(arg0 actor.ServerID, arg1 actor.Message) {
	m.ctrl.Call(m, "Send", arg0, arg1)
}

// Send indicates an expected call of Send
func (mr *MockServerGatewayMockRecorder) Send(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockServerGateway)(nil).Send), arg0, arg1)
}
