// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go

// Package mock_go_raft is a generated GoMock package.
package mock_go_raft

import (
	gomock "github.com/golang/mock/gomock"
	go_raft "github.com/sema/go-raft"
	reflect "reflect"
)

// MockServerGateway is a mock of ServerGateway interface
type MockServerGateway struct {
	ctrl     *gomock.Controller
	recorder *MockServerGatewayMockRecorder
}

// MockServerGatewayMockRecorder is the mock recorder for MockServerGateway
type MockServerGatewayMockRecorder struct {
	mock *MockServerGateway
}

// NewMockServerGateway creates a new mock instance
func NewMockServerGateway(ctrl *gomock.Controller) *MockServerGateway {
	mock := &MockServerGateway{ctrl: ctrl}
	mock.recorder = &MockServerGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockServerGateway) EXPECT() *MockServerGatewayMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockServerGateway) Send(to go_raft.ServerID, message go_raft.Message) {
	m.ctrl.Call(m, "Send", to, message)
}

// Send indicates an expected call of Send
func (mr *MockServerGatewayMockRecorder) Send(to, message interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockServerGateway)(nil).Send), to, message)
}
