// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpcserver/pb/server.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Kind                 string      `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	From                 string      `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string      `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Term                 uint64      `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LastLogTerm          uint64      `protobuf:"varint,5,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	LastLogIndex         uint64      `protobuf:"varint,6,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	VoteGrated           bool        `protobuf:"varint,7,opt,name=vote_grated,json=voteGrated,proto3" json:"vote_grated,omitempty"`
	PreviousLogTerm      uint64      `protobuf:"varint,8,opt,name=previous_log_term,json=previousLogTerm,proto3" json:"previous_log_term,omitempty"`
	PreviousLogIndex     uint64      `protobuf:"varint,9,opt,name=previous_log_index,json=previousLogIndex,proto3" json:"previous_log_index,omitempty"`
	LeaderCommit         uint64      `protobuf:"varint,10,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	LogEntries           []*LogEntry `protobuf:"bytes,11,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	Success              bool        `protobuf:"varint,12,opt,name=success,proto3" json:"success,omitempty"`
	MatchIndex           uint64      `protobuf:"varint,13,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	ProposalPayload      string      `protobuf:"bytes,14,opt,name=proposal_payload,json=proposalPayload,proto3" json:"proposal_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_135883c161650cfc, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Message) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *Message) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *Message) GetVoteGrated() bool {
	if m != nil {
		return m.VoteGrated
	}
	return false
}

func (m *Message) GetPreviousLogTerm() uint64 {
	if m != nil {
		return m.PreviousLogTerm
	}
	return 0
}

func (m *Message) GetPreviousLogIndex() uint64 {
	if m != nil {
		return m.PreviousLogIndex
	}
	return 0
}

func (m *Message) GetLeaderCommit() uint64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

func (m *Message) GetLogEntries() []*LogEntry {
	if m != nil {
		return m.LogEntries
	}
	return nil
}

func (m *Message) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Message) GetMatchIndex() uint64 {
	if m != nil {
		return m.MatchIndex
	}
	return 0
}

func (m *Message) GetProposalPayload() string {
	if m != nil {
		return m.ProposalPayload
	}
	return ""
}

type LogEntry struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Payload              string   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_135883c161650cfc, []int{1}
}
func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogEntry) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type SendMessagesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessagesResponse) Reset()         { *m = SendMessagesResponse{} }
func (m *SendMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessagesResponse) ProtoMessage()    {}
func (*SendMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_135883c161650cfc, []int{2}
}
func (m *SendMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessagesResponse.Unmarshal(m, b)
}
func (m *SendMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessagesResponse.Marshal(b, m, deterministic)
}
func (m *SendMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessagesResponse.Merge(m, src)
}
func (m *SendMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessagesResponse.Size(m)
}
func (m *SendMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessagesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*LogEntry)(nil), "LogEntry")
	proto.RegisterType((*SendMessagesResponse)(nil), "SendMessagesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SRServerClient is the client API for SRServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SRServerClient interface {
	SendMessages(ctx context.Context, opts ...grpc.CallOption) (SRServer_SendMessagesClient, error)
}

type sRServerClient struct {
	cc *grpc.ClientConn
}

func NewSRServerClient(cc *grpc.ClientConn) SRServerClient {
	return &sRServerClient{cc}
}

func (c *sRServerClient) SendMessages(ctx context.Context, opts ...grpc.CallOption) (SRServer_SendMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SRServer_serviceDesc.Streams[0], "/SRServer/SendMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &sRServerSendMessagesClient{stream}
	return x, nil
}

type SRServer_SendMessagesClient interface {
	Send(*Message) error
	CloseAndRecv() (*SendMessagesResponse, error)
	grpc.ClientStream
}

type sRServerSendMessagesClient struct {
	grpc.ClientStream
}

func (x *sRServerSendMessagesClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sRServerSendMessagesClient) CloseAndRecv() (*SendMessagesResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendMessagesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SRServerServer is the server API for SRServer service.
type SRServerServer interface {
	SendMessages(SRServer_SendMessagesServer) error
}

func RegisterSRServerServer(s *grpc.Server, srv SRServerServer) {
	s.RegisterService(&_SRServer_serviceDesc, srv)
}

func _SRServer_SendMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SRServerServer).SendMessages(&sRServerSendMessagesServer{stream})
}

type SRServer_SendMessagesServer interface {
	SendAndClose(*SendMessagesResponse) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type sRServerSendMessagesServer struct {
	grpc.ServerStream
}

func (x *sRServerSendMessagesServer) SendAndClose(m *SendMessagesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sRServerSendMessagesServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SRServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SRServer",
	HandlerType: (*SRServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessages",
			Handler:       _SRServer_SendMessages_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/grpcserver/pb/server.proto",
}

func init() { proto.RegisterFile("pkg/grpcserver/pb/server.proto", fileDescriptor_135883c161650cfc) }

var fileDescriptor_135883c161650cfc = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xb1, 0x93, 0x36, 0xce, 0x38, 0x49, 0xcb, 0xaa, 0xa0, 0x15, 0x07, 0xb0, 0x0c, 0x07,
	0x53, 0x21, 0x47, 0x6a, 0x1f, 0x80, 0x03, 0x42, 0x08, 0xa9, 0x20, 0xe4, 0x70, 0xb7, 0xb6, 0xf6,
	0x60, 0xac, 0xda, 0xde, 0xd5, 0xee, 0x36, 0x22, 0x8f, 0xc9, 0x1b, 0xa1, 0x9d, 0xb5, 0x43, 0x90,
	0xb8, 0xfd, 0xfb, 0xcd, 0xef, 0xf9, 0xc7, 0x9a, 0x81, 0x97, 0xea, 0xa1, 0xd9, 0x36, 0x5a, 0x55,
	0x06, 0xf5, 0x1e, 0xf5, 0x56, 0xdd, 0x6f, 0xbd, 0xca, 0x95, 0x96, 0x56, 0xa6, 0xbf, 0x67, 0xb0,
	0xf8, 0x82, 0xc6, 0x88, 0x06, 0x19, 0x83, 0xf9, 0x43, 0x3b, 0xd4, 0x3c, 0x48, 0x82, 0x6c, 0x59,
	0x90, 0x76, 0xec, 0x87, 0x96, 0x3d, 0x0f, 0x3d, 0x73, 0x9a, 0x6d, 0x20, 0xb4, 0x92, 0xcf, 0x88,
	0x84, 0x56, 0x3a, 0x8f, 0x45, 0xdd, 0xf3, 0x79, 0x12, 0x64, 0xf3, 0x82, 0x34, 0x4b, 0x61, 0xdd,
	0x09, 0x63, 0xcb, 0x4e, 0x36, 0x25, 0x15, 0xcf, 0xa8, 0x18, 0x3b, 0x78, 0x27, 0x9b, 0xef, 0xce,
	0xf3, 0x06, 0x36, 0x47, 0x4f, 0x3b, 0xd4, 0xf8, 0x8b, 0x9f, 0x93, 0x69, 0x35, 0x9a, 0x3e, 0x3b,
	0xc6, 0x5e, 0x41, 0xbc, 0x97, 0x16, 0xcb, 0x46, 0x0b, 0x8b, 0x35, 0x5f, 0x24, 0x41, 0x16, 0x15,
	0xe0, 0xd0, 0x27, 0x22, 0xec, 0x1a, 0x9e, 0x2a, 0x8d, 0xfb, 0x56, 0x3e, 0x9a, 0xbf, 0x71, 0x11,
	0x75, 0xba, 0x98, 0x0a, 0x53, 0xe4, 0x3b, 0x60, 0xff, 0x78, 0x7d, 0xec, 0x92, 0xcc, 0x97, 0x27,
	0x66, 0x1f, 0xfd, 0x1a, 0xd6, 0x1d, 0x8a, 0x1a, 0x75, 0x59, 0xc9, 0xbe, 0x6f, 0x2d, 0x87, 0x71,
	0x3e, 0x82, 0x1f, 0x88, 0xb1, 0x6b, 0x88, 0x5d, 0x27, 0x1c, 0xac, 0x6e, 0xd1, 0xf0, 0x38, 0x99,
	0x65, 0xf1, 0xcd, 0x32, 0xbf, 0x93, 0xcd, 0xc7, 0xc1, 0xea, 0x43, 0x01, 0x9d, 0x57, 0x2d, 0x1a,
	0xc6, 0x61, 0x61, 0x1e, 0xab, 0x0a, 0x8d, 0xe1, 0x2b, 0xfa, 0x8f, 0xe9, 0xe9, 0xfe, 0xb2, 0x17,
	0xb6, 0xfa, 0x39, 0x4e, 0xb4, 0xa6, 0x20, 0x20, 0xe4, 0x67, 0x79, 0x0b, 0x97, 0x4a, 0x4b, 0x25,
	0x8d, 0xe8, 0x4a, 0x25, 0x0e, 0x9d, 0x14, 0x35, 0xdf, 0xd0, 0x0a, 0x2e, 0x26, 0xfe, 0xcd, 0xe3,
	0xf4, 0x2b, 0x44, 0x53, 0xfa, 0x71, 0x37, 0xc1, 0xc9, 0x6e, 0xae, 0xe0, 0xcc, 0xa7, 0x84, 0x04,
	0xfd, 0xc3, 0xcd, 0x36, 0xf5, 0xf5, 0xab, 0x9d, 0x9e, 0xe9, 0x73, 0xb8, 0xda, 0xe1, 0x50, 0x8f,
	0x67, 0x62, 0x0a, 0x34, 0x4a, 0x0e, 0x06, 0x6f, 0xde, 0x43, 0xb4, 0x2b, 0x76, 0x74, 0x4d, 0xec,
	0x16, 0x56, 0xa7, 0x1e, 0x16, 0xe5, 0xa3, 0x7c, 0xf1, 0x2c, 0xff, 0xdf, 0xc7, 0xe9, 0x93, 0x2c,
	0xb8, 0x3f, 0xa7, 0x1b, 0xbc, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x3c, 0x32, 0x30, 0xa5,
	0x02, 0x00, 0x00,
}
